import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

with open(os.path.join(SCRIPT_DIR, 'train_data.json')) as f:
    existing = json.load(f)

# new filler data — paste the full JSON array you got here
new_fillers = [[{"text":"[TARGET] um [CONTEXT] um I don’t really know what to say here","label":1},{"text":"[TARGET] um [CONTEXT] I was, um, trying to call you earlier","label":1},{"text":"[TARGET] um [CONTEXT] um maybe we should wait a little longer","label":1},{"text":"[TARGET] um [CONTEXT] I think um we missed the correct exit","label":1},{"text":"[TARGET] um [CONTEXT] um can somebody explain this again","label":1},{"text":"[TARGET] um [CONTEXT] I was um honestly kind of confused","label":1},{"text":"[TARGET] um [CONTEXT] um I forgot where I parked the car","label":1},{"text":"[TARGET] um [CONTEXT] we should um probably leave now","label":1},{"text":"[TARGET] um [CONTEXT] um that’s not exactly what I meant","label":1},

{"text":"[TARGET] uh [CONTEXT] uh I think your microphone is muted","label":1},{"text":"[TARGET] uh [CONTEXT] I uh forgot to send the email","label":1},{"text":"[TARGET] uh [CONTEXT] uh maybe this isn’t the best idea","label":1},{"text":"[TARGET] uh [CONTEXT] can you uh repeat that one more time","label":1},{"text":"[TARGET] uh [CONTEXT] uh I wasn’t really paying attention","label":1},{"text":"[TARGET] uh [CONTEXT] we should uh probably start now","label":1},{"text":"[TARGET] uh [CONTEXT] uh I left my wallet at home","label":1},{"text":"[TARGET] uh [CONTEXT] I was uh trying to explain that earlier","label":1},{"text":"[TARGET] uh [CONTEXT] uh this line is taking forever","label":1},

{"text":"[TARGET] like [CONTEXT] like I didn’t even know they were coming","label":1},{"text":"[TARGET] like [CONTEXT] I was like really tired yesterday","label":1},{"text":"[TARGET] like [CONTEXT] like this whole thing feels unnecessary","label":1},{"text":"[TARGET] like [CONTEXT] we were like standing there for hours","label":1},{"text":"[TARGET] like [CONTEXT] like why would anyone do that","label":1},{"text":"[TARGET] like [CONTEXT] I was like honestly shocked","label":1},{"text":"[TARGET] like [CONTEXT] like nobody told me there was homework","label":1},{"text":"[TARGET] like [CONTEXT] it was like super awkward in there","label":1},{"text":"[TARGET] like [CONTEXT] like I seriously thought he was joking","label":1},

{"text":"[TARGET] you know [CONTEXT] you know I wasn’t expecting that answer","label":1},{"text":"[TARGET] you know [CONTEXT] it’s just you know kind of stressful","label":1},{"text":"[TARGET] you know [CONTEXT] you know maybe we should leave early","label":1},{"text":"[TARGET] you know [CONTEXT] I was you know trying my best","label":1},{"text":"[TARGET] you know [CONTEXT] you know this feels really weird","label":1},{"text":"[TARGET] you know [CONTEXT] it’s you know harder than it looks","label":1},{"text":"[TARGET] you know [CONTEXT] you know I completely forgot about that","label":1},{"text":"[TARGET] you know [CONTEXT] we were you know waiting outside forever","label":1},{"text":"[TARGET] you know [CONTEXT] you know I don’t really blame him","label":1},

{"text":"[TARGET] basically [CONTEXT] basically we missed the entire meeting","label":1},{"text":"[TARGET] basically [CONTEXT] I basically forgot everything I studied","label":1},{"text":"[TARGET] basically [CONTEXT] basically this app keeps crashing randomly","label":1},{"text":"[TARGET] basically [CONTEXT] we basically waited there all day","label":1},{"text":"[TARGET] basically [CONTEXT] basically nobody knew what was happening","label":1},{"text":"[TARGET] basically [CONTEXT] I was basically doing all the work","label":1},{"text":"[TARGET] basically [CONTEXT] basically we need to start over","label":1},{"text":"[TARGET] basically [CONTEXT] he basically ignored every message","label":1},{"text":"[TARGET] basically [CONTEXT] basically I have no clue anymore","label":1},

{"text":"[TARGET] so [CONTEXT] so I was thinking we could leave early","label":1},{"text":"[TARGET] so [CONTEXT] so what exactly are we doing here","label":1},{"text":"[TARGET] so [CONTEXT] I mean so nobody told me beforehand","label":1},{"text":"[TARGET] so [CONTEXT] so I accidentally deleted the folder","label":1},{"text":"[TARGET] so [CONTEXT] we were so just waiting outside","label":1},{"text":"[TARGET] so [CONTEXT] so that’s kind of awkward honestly","label":1},{"text":"[TARGET] so [CONTEXT] so are we meeting tomorrow too","label":1},{"text":"[TARGET] so [CONTEXT] I was so trying to explain that","label":1},{"text":"[TARGET] so [CONTEXT] so maybe we should call them first","label":1},

{"text":"[TARGET] okay [CONTEXT] okay I think I understand now","label":1},{"text":"[TARGET] okay [CONTEXT] okay maybe let’s slow down a bit","label":1},{"text":"[TARGET] okay [CONTEXT] I mean okay that’s kind of strange","label":1},{"text":"[TARGET] okay [CONTEXT] okay can someone explain this again","label":1},{"text":"[TARGET] okay [CONTEXT] we should okay probably leave now","label":1},{"text":"[TARGET] okay [CONTEXT] okay I honestly forgot about that","label":1},{"text":"[TARGET] okay [CONTEXT] okay this is getting confusing","label":1},{"text":"[TARGET] okay [CONTEXT] I was okay trying to fix it earlier","label":1},{"text":"[TARGET] okay [CONTEXT] okay maybe tomorrow will be better","label":1},

{"text":"[TARGET] right [CONTEXT] right I completely forgot about the deadline","label":1},{"text":"[TARGET] right [CONTEXT] right so we’re meeting at six","label":1},{"text":"[TARGET] right [CONTEXT] I mean right that’s understandable","label":1},{"text":"[TARGET] right [CONTEXT] right maybe we should wait outside","label":1},{"text":"[TARGET] right [CONTEXT] we were right kind of confused honestly","label":1},{"text":"[TARGET] right [CONTEXT] right nobody told me about the change","label":1},{"text":"[TARGET] right [CONTEXT] I was right trying to explain earlier","label":1},{"text":"[TARGET] right [CONTEXT] right this whole thing feels weird","label":1},{"text":"[TARGET] right [CONTEXT] right I think we’re ready now","label":1},

{"text":"[TARGET] well [CONTEXT] well I didn’t really expect that","label":1},{"text":"[TARGET] well [CONTEXT] well maybe we should just leave","label":1},{"text":"[TARGET] well [CONTEXT] I mean well that’s unfortunate","label":1},{"text":"[TARGET] well [CONTEXT] well nobody warned me about traffic","label":1},{"text":"[TARGET] well [CONTEXT] we were well kind of stuck there","label":1},{"text":"[TARGET] well [CONTEXT] well I honestly don’t know anymore","label":1},{"text":"[TARGET] well [CONTEXT] well are we starting or not","label":1},{"text":"[TARGET] well [CONTEXT] I was well trying to help","label":1},{"text":"[TARGET] well [CONTEXT] well this got awkward really fast","label":1},

{"text":"[TARGET] actually [CONTEXT] actually I didn’t even notice that","label":1},{"text":"[TARGET] actually [CONTEXT] I was actually trying to call you","label":1},{"text":"[TARGET] actually [CONTEXT] actually maybe we should rethink this","label":1},{"text":"[TARGET] actually [CONTEXT] actually I forgot my laptop today","label":1},{"text":"[TARGET] actually [CONTEXT] we were actually waiting for you outside","label":1},{"text":"[TARGET] actually [CONTEXT] actually this makes more sense now","label":1},{"text":"[TARGET] actually [CONTEXT] I actually didn’t mean it like that","label":1},{"text":"[TARGET] actually [CONTEXT] actually nobody expected that result","label":1},{"text":"[TARGET] actually [CONTEXT] actually I have no idea what happened","label":1},

{"text":"[TARGET] honestly [CONTEXT] honestly I don’t really care anymore","label":1},{"text":"[TARGET] honestly [CONTEXT] I was honestly kind of nervous","label":1},{"text":"[TARGET] honestly [CONTEXT] honestly this whole thing feels pointless","label":1},{"text":"[TARGET] honestly [CONTEXT] we were honestly just waiting around","label":1},{"text":"[TARGET] honestly [CONTEXT] honestly I forgot there was homework","label":1},{"text":"[TARGET] honestly [CONTEXT] honestly maybe we should cancel it","label":1},{"text":"[TARGET] honestly [CONTEXT] I honestly didn’t expect that answer","label":1},{"text":"[TARGET] honestly [CONTEXT] honestly this app is confusing me","label":1},{"text":"[TARGET] honestly [CONTEXT] honestly I have no energy today","label":1}]]  # ← paste your entire JSON array inside here

flat_fillers = [item for sublist in new_fillers for item in (sublist if isinstance(sublist, list) else [sublist])]
combined = existing + flat_fillers

print(f"Total: {len(combined)}")
print(f"Fillers: {sum(1 for d in combined if d['label'] == 1)}")
print(f"Non fillers: {sum(1 for d in combined if d['label'] == 0)}")

with open(os.path.join(SCRIPT_DIR, 'train_data.json'), 'w') as f:
    json.dump(combined, f, indent=2)

print("Saved.")