import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

TRAINING_DATA = [("Um, I think we should probably leave soon.", "um", 1),
("Um, can you give me a second to think?", "um", 1),
("Um, I didn’t really expect that answer.", "um", 1),
("Um, maybe we should try another route.", "um", 1),
("Um, that’s not exactly what I meant.", "um", 1),
("Um, do you still have the tickets with you?", "um", 1),
("Um, I forgot where I parked the car.", "um", 1),
("Um, this feels a little awkward honestly.", "um", 1),
("Um, are we supposed to sign in first?", "um", 1),
("Um, I don’t think that’s gonna work.", "um", 1),
("Um, could you repeat the last part again?", "um", 1),
("Um, I was actually talking about tomorrow.", "um", 1),
("Um, maybe I’m overthinking this whole thing.", "um", 1),
("Um, nobody told me the meeting got moved.", "um", 1),
("Um, should we wait for the others first?", "um", 1),
("Um, I didn’t even bring my laptop today.", "um", 1),
("Um, this line is taking forever to move.", "um", 1),
("Um, I guess we can start without him.", "um", 1),
("Um, that’s kind of a weird question.", "um", 1),
("Um, I honestly have no clue what happened.", "um", 1),

("Uh, I think your mic is muted.", "uh", 1),
("Uh, can someone explain this part again?", "uh", 1),
("Uh, I left my charger back at home.", "uh", 1),
("Uh, maybe we should slow down a bit.", "uh", 1),
("Uh, that’s definitely not what I expected.", "uh", 1),
("Uh, are we meeting here tomorrow too?", "uh", 1),
("Uh, I don’t really know how to answer that.", "uh", 1),
("Uh, this place looks completely different now.", "uh", 1),
("Uh, I thought you already paid for it.", "uh", 1),
("Uh, should I send the file again?", "uh", 1),
("Uh, this coffee tastes kind of strange.", "uh", 1),
("Uh, I forgot what I was about to say.", "uh", 1),
("Uh, maybe let’s not do that right now.", "uh", 1),
("Uh, nobody mentioned there’d be an exam today.", "uh", 1),
("Uh, I think we’re at the wrong building.", "uh", 1),
("Uh, could you move a little to the left?", "uh", 1),
("Uh, I honestly wasn’t paying attention.", "uh", 1),
("Uh, this app keeps crashing on my phone.", "uh", 1),
("Uh, maybe we should just call them directly.", "uh", 1),
("Uh, I didn’t realize it was this late already.", "uh", 1),

("Like, I didn’t even know she was coming.", "like", 1),
("Like, this whole thing feels really unnecessary.", "like", 1),
("Like, why would anyone agree to that?", "like", 1),
("Like, I barely slept last night at all.", "like", 1),
("Like, that’s honestly kind of embarrassing.", "like", 1),
("Like, nobody told me there was homework.", "like", 1),
("Like, we were standing there for an hour.", "like", 1),
("Like, I seriously thought he was joking.", "like", 1),
("Like, this is exactly why I’m frustrated.", "like", 1),
("Like, I don’t even remember saying that.", "like", 1),
("Like, are we supposed to pretend that’s normal?", "like", 1),
("Like, this meeting could’ve been an email.", "like", 1),
("Like, I honestly have no energy today.", "like", 1),
("Like, everything started going wrong at once.", "like", 1),
("Like, I was just trying to help.", "like", 1),

("I like this café because it’s quiet.", "like", 0),
("She doesn’t like spicy food very much.", "like", 0),
("I’d like to leave a little earlier today.", "like", 0),
("They like watching movies together on weekends.", "like", 0),
("I really like your new apartment layout.", "like", 0),
("Would you like another cup of coffee?", "like", 0),
("Kids usually like places with bright colors.", "like", 0),
("I like how simple this app feels.", "like", 0),
("He looks like his older brother.", "like", 0),
("I’d like some time to think about it.", "like", 0),
("You sound like you’re getting sick.", "like", 0),
("They like going on long drives at night.", "like", 0),
("I like when it rains during the evening.", "like", 0),
("This tastes like something my mom would cook.", "like", 0),
("She’d like a refund for the damaged item.", "like", 0),

("So, what are we supposed to do now?", "so", 1),
("So, I was thinking about changing jobs.", "so", 1),
("So, that’s basically the whole story.", "so", 1),
("So, are you coming with us or not?", "so", 1),
("So, I completely forgot about the assignment.", "so", 1),
("So, this is where everyone disappeared to.", "so", 1),
("So, what did the doctor actually say?", "so", 1),
("So, I guess we’re doing this again.", "so", 1),
("So, how long have you been waiting here?", "so", 1),
("So, nobody thought to tell me earlier?", "so", 1),
("So, that’s kind of a weird coincidence.", "so", 1),
("So, are we meeting again tomorrow morning?", "so", 1),
("So, I accidentally deleted the whole folder.", "so", 1),
("So, that’s why the internet stopped working.", "so", 1),
("So, what happens if this fails completely?", "so", 1),

("I was tired so I went home early.", "so", 0),
("She spoke so quietly that nobody heard her.", "so", 0),
("The bag was so heavy I couldn’t lift it.", "so", 0),
("He studied hard so he could pass the test.", "so", 0),
("It was so cold outside this morning.", "so", 0),
("I was hungry so I ordered extra food.", "so", 0),
("The movie was so long we left halfway through.", "so", 0),
("She smiled so brightly that everyone noticed.", "so", 0),
("I woke up late so I missed the train.", "so", 0),
("He whispered so softly I could barely hear him.", "so", 0),
("The room was so crowded we couldn’t move.", "so", 0),
("I practiced daily so my timing improved.", "so", 0),
("She ran so fast nobody could catch her.", "so", 0),
("It was so dark I couldn’t find my keys.", "so", 0),
("I saved money so I could buy a laptop.", "so", 0),

("Okay, I think I understand now.", "okay", 1),
("Okay, maybe we should try again later.", "okay", 1),
("Okay, that’s honestly kind of weird.", "okay", 1),
("Okay, let me think about that for a second.", "okay", 1),
("Okay, I didn’t expect this many people.", "okay", 1),
("Okay, are we finally ready to start?", "okay", 1),
("Okay, that’s probably not a good sign.", "okay", 1),
("Okay, I guess we’ll wait a little longer.", "okay", 1),
("Okay, can somebody explain what’s happening?", "okay", 1),
("Okay, I totally forgot about the deadline.", "okay", 1),
("Okay, maybe I’m just overreacting a bit.", "okay", 1),
("Okay, this actually makes a lot more sense.", "okay", 1),
("Okay, I think we’re going in circles now.", "okay", 1),
("Okay, that’s enough stress for one day.", "okay", 1),
("Okay, what exactly is the backup plan?", "okay", 1),

("The food was okay but nothing special.", "okay", 0),
("Your presentation was okay overall.", "okay", 0),
("I’m okay with waiting another hour.", "okay", 0),
("The movie was just okay honestly.", "okay", 0),
("Is it okay if I leave early today?", "okay", 0),
("Her grades were okay despite missing classes.", "okay", 0),
("The design looks okay on mobile devices.", "okay", 0),
("I’m okay now after getting some rest.", "okay", 0),
("The audio quality sounds okay to me.", "okay", 0),
("Everything turned out okay in the end.", "okay", 0),
("That solution is okay for a temporary fix.", "okay", 0),
("He said it was okay to reschedule.", "okay", 0),
("Your timing is okay but needs improvement.", "okay", 0),
("The battery life is okay for daily use.", "okay", 0),
("I’m not okay with people arriving this late.", "okay", 0),

("Right, I completely forgot about that.", "right", 1),
("Right, that’s exactly what I meant earlier.", "right", 1),
("Right, I should probably send that email now.", "right", 1),
("Right, so we’re meeting at six then.", "right", 1),
("Right, I didn’t realize today was Friday.", "right", 1),
("Right, that’s why the app kept crashing.", "right", 1),
("Right, I guess we don’t have much choice.", "right", 1),
("Right, let me grab my laptop first.", "right", 1),
("Right, I remember where I saw him before.", "right", 1),
("Right, this whole thing feels unnecessary.", "right", 1),
("Right, are we still doing the presentation today?", "right", 1),
("Right, that’s kind of awkward honestly.", "right", 1),
("Right, maybe we should leave before traffic starts.", "right", 1),
("Right, I think I finally understand the issue.", "right", 1),
("Right, so what happens after this step?", "right", 1),

("Turn right at the next traffic signal.", "right", 0),
("You got the right answer on the test.", "right", 0),
("That doesn’t feel right to me at all.", "right", 0),
("She was right about the weather changing.", "right", 0),
("Make sure the filename is spelled right.", "right", 0),
("I injured my right shoulder during practice.", "right", 0),
("He made the right decision by leaving early.", "right", 0),
("The right side of the screen is flickering.", "right", 0),
("You were absolutely right about the deadline.", "right", 0),
("Everything finally started going right for once.", "right", 0),
("The right tool makes debugging much easier.", "right", 0),
("I parked the car on the right side.", "right", 0),
("That answer sounds right based on the data.", "right", 0),
("You picked the right time to call me.", "right", 0),
("The right password finally unlocked the account.", "right", 0),

("Well, I didn’t see that coming.", "well", 1),
("Well, this is kind of awkward now.", "well", 1),
("Well, I guess we should get started.", "well", 1),
("Well, that’s definitely one way to do it.", "well", 1),
("Well, I honestly don’t know what happened.", "well", 1),
("Well, maybe we should slow down a bit.", "well", 1),
("Well, nobody warned me about the traffic.", "well", 1),
("Well, this meeting is taking forever.", "well", 1),
("Well, I completely forgot my wallet again.", "well", 1),
("Well, are we just gonna ignore that?", "well", 1),
("Well, that’s probably not a good idea.", "well", 1),
("Well, I think we’re finally making progress.", "well", 1),
("Well, I wasn’t expecting that answer honestly.", "well", 1),
("Well, maybe tomorrow will go better.", "well", 1),
("Well, what exactly are we supposed to do?", "well", 1),

("She sings really well during live performances.", "well", 0),
("The project went surprisingly well overall.", "well", 0),
("He handled the interview very well.", "well", 0),
("The app runs well even on old devices.", "well", 0),
("I slept well for the first time in days.", "well", 0),
("The patient recovered well after surgery.", "well", 0),
("They work well together as a team.", "well", 0),
("The engine performs well in cold weather.", "well", 0),
("She explained the concept really well.", "well", 0),
("The movie was well directed and emotional.", "well", 0),
("Everything ended well despite the confusion.", "well", 0),
("The software scales well under heavy traffic.", "well", 0),
("He adapted well to the new environment.", "well", 0),
("The speaker communicated the idea well.", "well", 0),
("That strategy worked well for our team.", "well", 0)]

def prepare_dataset():
    formatted = []
    for sentence, target, label in TRAINING_DATA:
        words = sentence.split()
        for i, word in enumerate(words):
            if word.lower() == target.lower():
                # get context window around the word
                start = max(0, i - 3)
                end = min(len(words), i + 4)
                context = " ".join(words[start:end])
                formatted.append({
                    "text": f"[TARGET] {target} [CONTEXT] {context}",
                    "label": label
                })
    
    with open(os.path.join(SCRIPT_DIR, "train_data.json"), "w") as f:
        json.dump(formatted, f, indent=2)
    
    print(f"Prepared {len(formatted)} training examples")
    return formatted

if __name__ == "__main__":
    prepare_dataset()